### ISSUE TITLE
PopupTrigger does not work with Ubuntu

### ISSUE THREAD

**Issue by thred** [thred/climate-tray#10]
PopupTrigger does not work with Ubuntu tray icons. With Gnome tray icons fail completely

**Comment by thred** [comment]
Ubuntu should work now (cannot test it), but Gnome does not support tray icons as a whole. I should find some other strategy instead, maybe display a "small" application with a large status icon an some text...

**Comment by StefanTT** [comment]
Confirmed, the popup now works in Ubuntu :+1:

**Comment by thred** [comment]
The Gnome issue is left open. Moved to new enhancement: #20
